### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by vbd** [kulinsky/colorizer#12]
It's not an issue, it is more of a i wish.
Currently I have no access to any rust environment. Could you please supply a windows binary?
I think it would help me a lot.
Thanks in advance.

**Comment by kulinsky** [comment]
Hi, I'll try to do this

**Comment by kulinsky** [comment]
added workflow for build for several systems, binaries can be downloaded from the following link https://github.com/kulinsky/colorizer/releases/tag/v2.1.0
please check Windows and if you find errors, create new issue

**Comment by vbd** [comment]
Just downloaded and tested for my usecase. Works great, thank you very much!
